package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    check(name == "Build") {
        "Unexpected name: '$name'"
    }
    name = "Prepare"

    expectSteps {
        script {
            scriptContent = "echo 'hello world'"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = """
                echo "Create Artifacts Folder"
                sh "mkdir ${'$'}{env.ArtifactsFolder}"
            """.trimIndent()
        }
    }
}
