package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'StagingToQa'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("StagingToQa")
    name = "Staging to QA"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            scriptContent = """
                // echo "Pipeline run triggered remotely by '${'$'}{params.TriggeredBy}' for the following applications (including tests): '${'$'}{params.ApplicationScopeWithTests}'"
                // echo 'Retrieving latest application tags from Development environment...'
                sh "python -m outsystems.pipeline.fetch_lifetime_data --artifacts \"${'$'}ArtifactsFolder}\" --lt_url ${'$'}{LifeTimeEnvironmentURL} --lt_token ${'$'}{AuthorizationToken} --lt_api_version ${'$'}{LifeTimeAPIVersion}
                
                // echo 'Deploying latest application tags to Regression...'
                // sh "python -m outsystems.pipeline.deploy_latest_tags_to_target_env --artifacts \"${'$'}{ArtifactsFolder}\" --lt_url ${'$'}{LifeTimeEnvironmentURL} --lt_token ${'$'}{AuthorizationToken} --lt_api_version ${'$'}{LifeTimeAPIVersion} --source_env \"${'$'}{DevelopmentEnvironment}\" --destination_env \"${'$'}{AcceptanceEnvironment}\" --app_list \"${'$'}{ApplicationScopeWithTests}\""
            """.trimIndent()
        }
    }
}))

